#!/usr/bin/env python3
"""
Simple OAuth callback server that captures the authorization code from GitHub.

Usage:
    python oauth-callback-server.py [--port 3000]

EXTRA: use ngrok to expose localhost for testing with GitHub:
    ngrok http 3000 

After starting the server, visit the authorization URL generated by ghapp-user-token.py.
The server will capture the code and display it.
"""

import argparse
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
import sys
import warnings

# Suppress urllib3 NotOpenSSLWarning
warnings.filterwarnings('ignore', message='urllib3 v2 only supports OpenSSL')


class OAuthCallbackHandler(BaseHTTPRequestHandler):
    """Handle OAuth callback requests."""
    
    def do_GET(self):
        """Handle GET requests from GitHub OAuth redirect."""
        parsed_url = urlparse(self.path)
        params = parse_qs(parsed_url.query)
        
        code = params.get('code', [None])[0]
        error = params.get('error', [None])[0]
        
        if error:
            self.send_response(400)
            self.send_header('Content-type', 'text/html')
            self.end_headers()
            message = f"<h1>Authorization Error</h1><p>Error: {error}</p>"
            self.wfile.write(message.encode())
            print(f"\nError: {error}")
        elif code:
            self.send_response(200)
            self.send_header('Content-type', 'text/html')
            self.end_headers()
            message = f"""
            <h1>Authorization Successful</h1>
            <p>Code: <code>{code}</code></p>
            <p>Copy the code above and use it with create-oauth-token.py</p>
            """
            self.wfile.write(message.encode())
            print(f"\nAuthorization code captured: {code}")
            print("Use this code with create-oauth-token.py")
        else:
            self.send_response(400)
            self.send_header('Content-type', 'text/html')
            self.end_headers()
            message = "<h1>Invalid Request</h1><p>No code or error parameter found.</p>"
            self.wfile.write(message.encode())
    
    def log_message(self, format, *args):
        """Suppress default logging."""
        pass


def main():
    parser = argparse.ArgumentParser(description="OAuth Callback Server")
    parser.add_argument(
        "--port",
        required=False,
        default=3000,
        type=int,
        help="Port to listen on (default: 3000)",
    )
    args = parser.parse_args()
    
    server_address = ('localhost', args.port)
    httpd = HTTPServer(server_address, OAuthCallbackHandler)
    
    print(f"OAuth callback server listening on http://localhost:{args.port}")
    print("Waiting for GitHub authorization callback...")
    print("Press Ctrl+C to stop the server")
    
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nServer stopped")
        sys.exit(0)


if __name__ == "__main__":
    main()
